# .devcontainer/docker-compose.yml
version: '3.8'

services:
  # Serviço 1: Banco de Dados
  postgres-db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432" # Expõe a porta do Postgres para o seu app
    environment:
      - POSTGRES_USER=findash
      - POSTGRES_PASSWORD=findash
      - POSTGRES_DB=findash_db
    volumes:
      - postgres-data:/var/lib/postgresql/data # Garante que os dados persistam

  # Serviço 2: Mensageria
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"   # Porta do protocolo AMQP
      - "15672:15672" # Porta do painel de admin web
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  postgres-data: # Define o volume